### ISSUE TITLE
issue 1

### ISSUE THREAD

**Issue by lordmen99** [TakuSemba/docker-nginx-rtmp#1]
still not build, i get this message =

 docker build -t nginx_rtmp
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | - [flags]

Build an image from a Dockerfile

**Comment by lordmen99** [comment]
http://prntscr.com/iadcum

working now..

**Comment by TakuSemba** [comment]
good 👍
